os:
  - linux

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - libudev-dev
      - libusb-1.0-0-dev
      - autotools-dev
      - autoconf
      - automake
      - libtool

before_install:
  - wget https://github.com/signal11/hidapi/archive/master.zip -O /tmp/hidapi.zip
  - unzip /tmp/hidapi.zip -d /tmp
  - cd /tmp/hidapi-master
  - ./bootstrap
  - ./configure --prefix=`pwd`/_local_install
  - make
  - make install
  - export PKG_CONFIG_PATH="`pwd`/_local_install/lib/pkgconfig:$PKG_CONFIG_PATH"
  - cd -

language: c

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - export
  - make
