sudo: required

language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libudev-dev libusb-1.0-0-dev autotools-dev autoconf automake libtool
  - wget https://github.com/signal11/hidapi/archive/master.zip -O /tmp/hidapi.zip
  - unzip /tmp/hidapi.zip -d /tmp
  - cd /tmp/hidapi-master
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd -
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update
  - sudo apt-get install --only-upgrade cmake

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - make
